robotiq_c2:
  # publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # position controller
  robotiq_85_left_knuckle_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_left_knuckle_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
